before_script:
  - apt-get update
  - apt-get -y install ros-humble-can-msgs ros-humble-nmea-msgs ros-humble-geographic-msgs ros-humble-diagnostic-updater ros-humble-robot-localization ros-humble-pcl-ros

stages:
  - build
  - test

build_project:
  image: althack/ros2:humble-full
  stage: build
  script:
    - git config --global url."https://oauth2:${CI_WORKER_CI_TOKEN}@github.com/".insteadOf "https://github.com/"
    - colcon build
  artifacts:
    paths:
      - build/*
      - log/*
      - install/*

test_project:
  image: althack/ros2:humble-full
  stage: test
  script:
    - source install/setup.bash
    - colcon test --return-code-on-test-failure
