name: CI Workflow

on:
  push:
    branches:
      - main
      - 04_12_oli
  pull_request:
    branches:
      - main
      - 04_12_oli
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run CI on'
        required: true
        default: '04_12_oli'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up ROS2 Humble
        run: |
          sudo apt-get update
          sudo apt-get -y install ros-humble-can-msgs ros-humble-nmea-msgs ros-humble-geographic-msgs ros-humble-diagnostic-updater ros-humble-robot-localization ros-humble-pcl-ros

      - name: Configure Git for CI
        run: |
          git config --global url."https://oauth2:${{ secrets.CI_WORKER_CI_TOKEN }}@github.com/".insteadOf "https://github.com/"
      
      - name: Build with colcon
        run: colcon build
      
      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-logs
          path: |
            build/
            log/
            install/

  test:
    name: Test Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Source Build Files
        run: |
          source install/setup.bash

      - name: Run Tests
        run: colcon test --return-code-on-test-failure
